

input: ./CHEUI_read_level_A_B.sorted.txt 

# sample labels used to run /scripts/CHEUI_predict_model1.py
sample_labels:
    condition1:
        rep1: A_rep1
    condition2:
        rep1: B_rep1

# cutoff used to classify methylated reads
upper_cutoff: 0.7

# cutoff used to classify unmethylated reads
lower_cutoff: 0.3

out: ./CHEUI_differentialRNAMod_A_vs_B.txt
